### ISSUE TITLE
How to get 'test_bbox_results.json'

### ISSUE THREAD

**Issue by aricl3** [ilnehc96/HKU-DASC7606-A1#12]
I found that the 'test_bbox_results.json' file exists in the test_submission.py test file. At what stage is this file generated? Is it automatically generated by the program or does it need to be generated manually?

```
# load results in COCO evaluation tool
    coco_true = dataset_test.coco
    coco_pred = coco_true.loadRes('test_bbox_results.json')
```

**Comment by ilnehc96** [comment]
It will automatically saved when you run tesy.py.

If it is not saved, the most possible issue is that your trained model learns nothing and there is not prediction. There could be bugs in your implementation, especially the loss part (since most of students can get correct model parts' implementation).
